import { Signer, VoidSigner } from "@ethersproject/abstract-signer";
import { BigNumber, BigNumberish, FixedNumber } from "@ethersproject/bignumber";
import { Bytes, BytesLike, Signature } from "@ethersproject/bytes";
import * as constants from "@ethersproject/constants";
import {
  CallOverrides,
  Contract,
  ContractFactory,
  ContractFunction,
  ContractInterface,
  ContractReceipt,
  ContractTransaction,
  Event,
  EventFilter,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
} from "@ethersproject/contracts";
import { Logger, ErrorCode as errors } from "@ethersproject/logger";
import * as providers from "@ethersproject/providers";
import { getDefaultProvider } from "@ethersproject/providers";
import { Transaction, UnsignedTransaction } from "@ethersproject/transactions";
import { Wallet } from "@ethersproject/wallet";
import { Wordlist, wordlists } from "@ethersproject/wordlists";

import { version } from "./_version";
import * as utils from "./utils";

////////////////////////
// Types

////////////////////////
// Compile-Time Constants

// This is generated by "npm run dist"

const logger = new Logger(version);

////////////////////////
// Types
////////////////////////
// Exports
export {
  Signer,
  Wallet,
  VoidSigner,
  getDefaultProvider,
  providers,
  Contract,
  ContractFactory,
  BigNumber,
  FixedNumber,
  constants,
  errors,
  logger,
  utils,
  wordlists,
  ////////////////////////
  // Compile-Time Constants
  version,
  Wordlist,
};
export type {
  ////////////////////////
  // Types
  ContractFunction,
  ContractReceipt,
  ContractTransaction,
  Event,
  EventFilter,
  Overrides,
  PayableOverrides,
  CallOverrides,
  PopulatedTransaction,
  ContractInterface,
  BigNumberish,
  Bytes,
  BytesLike,
  Signature,
  Transaction,
  UnsignedTransaction,
};
